matrix:
  include:
    - language: node_js
      node_js:
        - lts/*
      dist: bionic
      before_install:
        - eval "$(gimme 1.14.x)"
      install:
        - ./install.sh
        - sudo apt-get install -y softhsm2
        - npm install --global mocha
        - ./test/hsm.sh
      script:
        - npm start
        - npm test
