matrix:
  include:
    - language: node_js
      node_js:
        - "10"
      dist: bionic
      before_install:
        - eval "$(gimme 1.12.x)"
      install:
        - ./install.sh
        - cd common/nodejs; npm install ; cd - ;
        - cd common/nodejs/fabric-network; npm install ; cd -;
        - sudo apt-get install -y softhsm2
      script:
        - ./docker.sh
        - node cc/golang/diagnose
        - node test
        - ./test/hsm.sh