matrix:
  include:
    - language: node_js
      node_js:
        - "10"
      dist: bionic
      before_install:
        - eval "$(gimme 1.12.x)"
      install:
        - ./install.sh
        - sudo apt-get install -y softhsm2
      script:
        - ./docker.sh
        - mocha cc/golang/diagnose/test
        - node cc/golang/diagnose/diagnoseInvoke.js
        - node test
        - ./test/hsm.sh