dist: bionic
_bash_job: &_bash_job
  language: bash
  install:
    - ./common/install.sh softHSMInstall
  script:
    - ./test/hsm.sh
_nodejs_job: &_nodejs_job
  language: node_js
  node_js:
    - lts/*
  install:
    - eval "$(gimme 1.14.x)"
    - ./common/install.sh softHSMInstall
    - ./install.sh
    - npm install --global mocha
  script:
    - npm start
    - npm test
jobs:
  fast_finish: true
  include:
    - os: linux
      before_install:
        - sudo apt update
      <<: *_nodejs_job
    - os: osx
      before_install:
        - brew update
      <<: *_nodejs_job
    - os: osx
      before_install:
        - brew update
      <<: *_bash_job
    - os: linux
      before_install:
        - sudo apt update
      <<: *_bash_job