language: node_js
os:
  - linux
  - osx
osx_image: xcode11
node_js:
  - "10"
dist: bionic
before_install:
  - eval "$(gimme 1.13.x)"
install:
  - curl --silent --show-error https://raw.githubusercontent.com/davidkhala/node-utils/master/install.sh | bash -s nodeGYPDependencies
  - npm config set package-lock false
  - npm install
  - sudo apt-get install -y softhsm2
  - cd common; ./install.sh fabricInstall; cd -
  - ./install.sh updateChaincode
script:
  - ./docker.sh
  - node cc/golang/diagnose/test/
  - node test
  - ./test/hsm.sh


