matrix:
  include:
    - language: node_js
      node_js:
        - "10"
      dist: bionic
      before_install:
        - eval "$(gimme 1.12.x)"
      install:
        - ./install.sh
        - npm install
        - sudo apt-get install -y softhsm2
      before_script:
        - ./docker.sh
      script:
        - cd config; ls ;  cd $TRAVIS_BUILD_DIR
        - node cc/golang/diagnose/test/
        - node test
        - ./test/hsm.sh

