matrix:
  include:
    - language: node_js
      node_js:
        - "10"
        - "12"
      dist: bionic
      before_install:
        - eval "$(gimme 1.14.x)"
      install:
        - ./install.sh
        - sudo apt-get install -y softhsm2
        - npm install --global mocha
      script:
        - ./docker.sh
        - npm test
        - ./test/hsm.sh
