language: go
dist: bionic
os:
  - osx
  - linux
go:
  - "1.14"
install:
  - ./common/install.sh softHSMInstall
#_shared_bash_job: &_shared_bash_job
#  language: bash
#  install:
#    - ./common/install.sh softHSM
#  script:
#    - ./test/hsm.sh
#_shared_nodejs_job: &_shared_nodejs_job
#  language: node_js
#  node_js:
#    - lts/*

#  install:
#    - ./install.sh
#    - ./common/install.sh softHSM
#    - npm install --global mocha
#  script:
#    - npm start
#    - npm test