dist: bionic
os:
  - linux
  - osx
before_install:
  - eval "$(gimme 1.14.x)"
  - ./install.sh
  - sudo apt-get install -y softhsm2
before_script:
  - ./test/hsm.sh
jobs:
  fast_finish: true
  include:
    - language: node_js
      node_js:
        - lts/*
      install:
        - npm install --global mocha
      script:
        - npm start
        - npm test
