dist: bionic
osx_image: xcode11
os:
  - linux
  - osx
services:
  - docker
language: node_js
node_js:
  - lts/*
before_install:
  - |
    if [[ $(uname) == "Darwin" ]]; then
      brew update;
      brew cask install docker
      open -a Docker
    else
      sudo apt update;
    fi
install:
  - eval "$(gimme 1.14.x)"
  - ./common/install.sh softHSMInstall
  - ./install.sh
script:
  - ./test/hsm.sh
  - npm start
  - npm test
