definitions:
  model.ProposalResult:
    properties:
      proposal-proto:
        type: string
      txid:
        type: string
    type: object
info:
  contact:
    email: david-khala@hotmail.com
  title: github.com/davidkhala/delphi-fabric/app
  version: v0.0.0
paths:
  /fabric/ping:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: fabric channel name
        in: path
        name: channel
        required: true
        type: string
      - description: fabric chaincode name
        in: formData
        name: chaincode
        required: true
        type: string
      - description: certificate of signer
        in: formData
        name: creator
        required: true
        type: string
      - description: Optional. chaincode version
        in: formData
        name: version
        type: string
      - description: chaincode args, including function name [fcn]
        in: formData
        name: args
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ProposalResult'
swagger: "2.0"
