name: ubuntu

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: true
      - uses: davidkhala/setup-dockerode@main
      - uses: actions/setup-go@main
        with:
          go-version: 1.20
      - run: npm install
      - uses: actions/checkout@main
        with:
          repository: davidkhala/chaincode
          path: chaincode
      - run: npm start
        timeout-minutes: 30
        env:
          binPath: common/bin
          channelName: allchannel
      - run: npm test
  softHSM:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: true
      - run: ./common/install.sh softHSMInstall
      - run: ./test-hsm/hsm.sh