on:
  workflow_call:
    inputs:
      os:
        default: ubuntu-latest
        required: false
        type: string
jobs:
  nodejs:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@main
        with:
          submodules: true
      - uses: actions/setup-node@main
        with:
          node-version: 14.x
      - uses: actions/setup-go@main
        with:
            go-version: 1.16
      - run: ./install.sh
      - run: npm start
        timeout-minutes: 30
      - run: npm test
