name: Github CI

on:
  push:
    branches:
      - master
  workflow_dispatch:
  workflow_call:
    inputs:
      os:
        default: ubuntu-latest
        required: false
        type: string
jobs:
  nodejs:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@main
        with:
          submodules: true
      - uses: actions/setup-node@main
        with:
          node-version: 14.x
      - run: ./install.sh
      - run: npm start
        timeout-minutes: 30
      - run: npm test
  softHSM:
    runs-on: ubuntu-latest
    steps:
      - run: ./common/install.sh softHSMInstall
      - run: ./test-hsm/hsm.sh