name: Node.js CI

on:
  push:
    branches:
     - master
  workflow_dispatch:
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: ./common/install.sh softHSMInstall
    - run: ./install.sh
    - run: ./test-hsm/hsm.sh
    - run: npm start
      timeout-minutes: 30
    - run: npm test
