name: Node.js Github CI

on:
  push:
    branches:
     - master
  workflow_dispatch:
jobs:
  e2e:
    strategy:
      matrix:
        os: [ubuntu-latest, oracle]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@main
      with:
        submodules: true
    - uses: actions/setup-node@main
      with:
        node-version: 14.x
    - run: ./common/install.sh softHSMInstall
    - run: ./install.sh
    - run: ./test-hsm/hsm.sh
    - run: npm start
      timeout-minutes: 30
    - run: npm test
