name: Self-host runner

on:
  workflow_dispatch:
jobs:
  e2e:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
        with:
          submodules: true
      - uses: docker-practice/actions-setup-docker@master
      - uses: davidkhala/delphi-fabric/.github/workflows/ci.yml@master
        with:
          os: self-hosted
