name: ubuntu

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  ubuntu:
    uses: davidkhala/delphi-fabric/.github/workflows/ci.yml@master
    with:
      os: ubuntu-latest
  softHSM:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: true
      - run: ./common/install.sh softHSMInstall
      - run: ./test-hsm/hsm.sh